### ISSUE TITLE
エネミーが透けて奥のほうのメッシュが貫通して見えてしまっている

### ISSUE THREAD

**Issue by MelLilye** [MelLilye/Bakemonobakari#347]
![KappaBP 2021_09_16 18_29_34](https://user-images.githubusercontent.com/72246455/133587811-f4bc6400-0807-4758-8d88-659bf6342b8e.png)

**Comment by Take515** [comment]
ゲーム上だと正常に描画されるけど、ビューポート上だとそうなっているよね。
