### ISSUE TITLE
ボス河童にダメージを与えた際にちび河童が残っているとうるさい

### ISSUE THREAD

**Issue by beeno-k** [MelLilye/Bakemonobakari#436]
ボス河童にダメージを与えた際に元々いるちび河童のDes()関数を作動させてちび河童を消しているが、Des()の中に音を鳴らす処理が含まれているため残っているちび河童の数の撃破音が同時に鳴る。
（もっとも、ボスにダメージを与えた際にプレイヤーが飛ばされない不具合が解消されればボスにダメージを与える際に画面上に残せるちび河童はせいぜい2体ぐらいに収まるはずなので、優先して修正する必要はない不具合だと思われる）

**Comment by MelLilye** [comment]
現在陳くんが対応中
